### ISSUE TITLE
Won't run

### ISSUE THREAD

**Issue by dovy** [Figedi/react-native-soundboard#1]
I can't get this running with the latest Redux. Are you using it anywhere? I'd like to see what it builds. No screenshots after all...  ;)

**Comment by Figedi** [comment]
Hey, I'm using it privately on my phone yeah. Do you have any error logs, why it doesnt run?  Note that my asset-library is in gitignore, thus you need to manually add it. 
I'm writing a Readme and take some screenshots later this weekend :)

**Comment by macasas** [comment]
Hi Figedi, I think you are right because running after cloning gives me 

The following build commands failed:
    CpResource assets build/Build/Products/Release-iphonesimulator/sounds.app/assets
(1 failure)

but what is assets?  It doesn't appear to be an xcode asset folder but I tried that, no images appear, tried a standard folder, nothing, and then tried it is src/constants as well but cannot work it out? Can you please explain where I am being stupid?

BTW, during the process of browsing through the app I can see that you have built this with an excellent layout, and it provides a good example of redux, something I am just trying to get my head around, so thank you and well done!

**Comment by Figedi** [comment]
Hey @macasas,

Assets contain static files. In this case it contains preview-images and soundclips. I copy the assets in the build step in order to access them later on the device locally. You can lookup the file-structure in `src/constants/`, or in `short:

```
<root>:
  assets:
    images: 
      <category>:
        <imagename>.{png,jpg,...}
```

Same applies for soundfiles, but in the sounds-folder

**Comment by macasas** [comment]
Hey Felix

Thanks for your reply.  I did eventually figure it out, I got confused over the icon in Xcode. When the assets didn’t exist it was showing a document icon, then when I created an asset folder I forgot to add it to the Xcode project.

Even though it is now working, I have 17 items in tab 1 but it only shows 12, same for other tabs.  Is this a known error or is it something else I am doing wrong?  Probably :-)

Where did you learn your coding style, I would like improve?

Thanks again.
Dave

On 31 October 2016 at 07:33:17, Felix Kaminski (notifications@github.com) wrote:

Hey @macasas,

Assets contain static files. In this case it contains preview-images and soundclips. I copy the assets in the build step in order to access them later on the device locally. You can lookup the file-structure in src/constants/, or in `short:

<root>:
  assets:
    images:  
      <category>:
        <imagename>.{png,jpg,...}
Same applies for soundfiles, but in the sounds-folder

**Comment by Figedi** [comment]
I'm closing this issue, the provided README should now clarify how to build the project
